UIAccessibility changes
xhacker/TEAChart pull request #20
Opened 2017-03-10 15:32 UTC by mathewa6

These are the modifications made in TEAChart to enable accessible use of Bar, Contribution and Clock charts as described in issue #19 .

2017-03-25 09:05 UTC, xhacker requested changes
Looks good! Just one minor comment.

2017-03-25 09:05 UTC, xhacker commented on TEAChart/TEAClockChart.m
> +
Empty line not necessary.

2017-03-25 19:17 UTC, mathewa6 commented
Thanks!

 I just made the correction! Let me know if there's anything else.

2017-04-16 08:24 UTC, merged

2017-04-16 08:25 UTC, xhacker commented
Thank you! 💯